# Generated by Django 4.2.23 on 2025-07-31 03:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='garment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('color', models.CharField(max_length=100, verbose_name='色')),
                ('cleated', models.DateField(auto_now_add=True, verbose_name='作成日時')),
            ],
        ),
    ]
