# Generated by Django 4.2.23 on 2025-07-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='type',
            field=models.CharField(default='未指定', max_length=100, verbose_name='分類'),
        ),
    ]
