# Generated by Django 4.2.23 on 2025-07-31 07:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0002_garment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='coordinate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('tops', models.CharField(max_length=100, null=True, verbose_name='トップス')),
                ('bottoms', models.CharField(max_length=100, null=True, verbose_name='ボトムス')),
                ('outer', models.CharField(max_length=100, null=True, verbose_name='アウター')),
                ('inner', models.CharField(max_length=100, null=True, verbose_name='インナー')),
                ('accessory', models.CharField(max_length=100, null=True, verbose_name='アクセサリー')),
                ('additional1', models.CharField(max_length=100, null=True, verbose_name='追加１')),
                ('additional2', models.CharField(max_length=100, null=True, verbose_name='追加２')),
                ('cleated', models.DateField(auto_now_add=True, verbose_name='作成日時')),
            ],
        ),
    ]
