# Generated by Django 4.2.23 on 2025-07-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0003_coordinate'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='temperature',
            field=models.CharField(max_length=100, null=True, verbose_name='気温設定'),
        ),
    ]
